# Generated by Django 4.2.5 on 2023-11-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0002_remove_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalattraction',
            name='image',
            field=models.ImageField(blank=True, upload_to='cultural_attraction/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='destinations/'),
        ),
    ]
